# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Jake's Blog
tagline:          'A series of ramblings about code among other things'
description:      "Because I probably don't have anything better to do" # later try switching htis to quotes and having don't on the inside
url:              http://jakesyl.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Jake '
  url:            https://twitter.com/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jakesyl/
